config/routes.rb
Rails.application.routes.draw do
 root "users#index"
 resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
#validates_date :DOB, :before => lambda { Date.current }
end

app/models/change.rb
class Change < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
validates :name, presence: true, format: { with: /\A[a-zA-Z\s]+\Z/i, message: "Only letters are allowed"}
validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "invalid email"}
validate :date_of
validates :password, presence: true,  confirmation: true , length: {minimum: 8}
validates :password_confirmation, presence: true, length: {minimum: 8}
def date_of
	if dob.present? && dob > Date.today
		errors.add(:dob, "date should be in past")
	end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
	@user = User.new
end

def show
	@user = User.find_by(params[:user_id])	
end

def index
	
end

def create
	@user = User.new(user_params)
	if @user.save
	redirect_to @user
	else
	render 'new'
	end
end

private
def user_params
	params.require(:user).permit(:name, :email, :dob, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
   
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="alert alert-success alert-dismissable fade in">
	<h3> Create New Account </h3>
<%= link_to 'Create Account', new_user_path ,class: "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="row bg">
  <div class="col-xs-4 col-md-offset-4">
    <%= bootstrap_form_for :user, url: users_path do |f| %>
    
    <% if @user.errors.any? %>
    <div class="alert alert-danger ">
    <h1>Errors:</h1>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li>          
              <%= message %>
      </li>
      <% end %>
    </ul>
    </div>
   
    <% end %>
    <div class= "form-signin">
    <h1><center>Sign Up</center></h1>
    <div class=" form-group form-group-lg ">
      <%= f.text_field :name , placeholder: "name"%><br>

      <%= f.email_field :email, placeholder: "email " %><br>

      <%= f.date_field :dob %><br>

      <%= f.password_field :password, placeholder: "password" %><br>

      <%= f.password_field :password_confirmation, placeholder: "confirm password" %><br>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="alert alert-success alert-dismissable fade in">
<h1>Congo!! user is created</h1>
</div>